[package]
name = "stochasta"
version = "0.4.0"
authors = ["Manuel Krebs <me@leun4m.de>"]
edition = "2021"
description = "A simple stochastic analysis library"
readme = "README.md"
repository = "https://github.com/leun4m/stochasta/"
license = "MIT OR Apache-2.0"
keywords = ["stochastic", "probability"]
categories = ["mathematics"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10"
num-rational = "0.4"
serde = { version = "1.0", optional = true, features = ["derive"] }
