[package]
name = "stochasta"
version = "0.1.0"
edition = "2021"
authors = ["Manuel Krebs <me@leun4m.de>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-rational = "0.4"
serde = { version = "1.0", optional = true, features = ["derive"] }
