name: Crate Publish

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  call-workflow:
    uses: leun4m/stochasta/.github/workflows/test.yml@main
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cargo login
      run: cargo login ${{ secrets.CRATES_IO_TOKEN }}
    - name: Publish
      run: cargo publish
