name: Rust Test

on:
  push:
    branches: [ develop, main ]
  pull_request:
    # Any pull request
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Check Format
      run: cargo fmt --check
    - name: Check Code
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Run tests
      run: cargo test --verbose
